name: Reporte de Issue
description: Reportes de Issue.
title: "Titulo descriptivo del issue"
labels: ["bug", "issue"]
projects: ["CDC", "DC v2"]
assignees:
  - ops-infra
body:
  - type: markdown
    attributes:
      value: |
        Gracias por subir el reporte de error. Para ayudarnos a resolver el problema, por favor completa la siguiente información.
  - type: input
    id: id
    attributes:
      label: ID Shield / ID Job LM / Other
      description: por favor nos indicas si tienes una información para poder trackar el issue
      placeholder: Por ejemplo ID Shield 123812
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Nos puedes contar que sucedió?
      description: Recordá que podes agregar imagenes y logs para ayudarnos a entender mejor el problema.
      placeholder: Explicación del problema
      value: "Tengo el siguiente problema..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: En que versión de CDC estas teniendo el problema
      options:
        - CDC (Default)
        - DC v2
      default: 0
    validations:
      required: true
  - type: dropdown
    id: where
    attributes:
      label: En que parte del flujo tuviste el problema
      multiple: true
      options:
        - Automatización
        - Shield
        - Job LM
        - Frontend
        - Backend
        - Otro
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: por favor si tienes logs o código que apoye al bug.
      render: shell

  - type: textarea
    id: reproducir
    attributes:
      label: Pasos para Reproducir el problema
      description: Necesitamos que por favor nos indiques de que manera podemos reproducir el problema. por ejemplo si el error es no poder cambiar un TTL, en el ttl puse letras o valor fuera de rango
      render: shell

  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento Esperado
      description: Entender el comportamiento esperado
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Compromiso de Seguimiento
      description: Recuerde que este es un compromiso de seguimiento del bug. 
      options:
        - label: Acepto acompañar al seguimiento de resolución de este bug como usuario
          required: true
